# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Build
      run: dotnet build --configuration Release -r linux-arm64 --self-contained
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish --no-build --configuration Release -r linux-arm64 --self-contained -o net-payments-webserver
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: net-payments-webserver
        path: net-payments-webserver
        if-no-files-found: error
        retention-days: 10
    - name: action-upload-to-s3
      uses: wixplosives/action-upload-to-s3@v10
      with:
        # AWS Access key id (short one)
        accessKeyId: $AWS_S3_ACCESSKEYID
        # AWS Secret access key  (long one)
        secretAccessKey: $AWS_S3_SECRETACCESSKEY
        # bucket name
        awsBucket: $AWS_S3_AWSBUCKET
        # subfolder in bucket to upload data to
        #s3Subfolder: 
        # sourcefolder to upload
        sourceFolder: net-payments-webserver
        # tags to set for uploaded files "Business Unit=core3&gitref=someverylongref"
        # tags: 
        #  Name of the virtual project to create link.Usefull for creating latest version links.
        #publishAsVirtualProject: # optional
        # file in s3Subfolder to upload
        #specificFile: # optional
